### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Resy31** [Resy31/furima_28722#9]
# URL
https://furima-28722.herokuapp.com/

# Basic認証
ID：resy31
PASS：3308

# 出品者
Mail：test@jp
PASS：test11

# 購入者
Mail：tester@test
PASS：test11

# PAY.JP
番号：4242424242424242
期限：3/23
CVC：123

**Comment by MasaakiTanabashi** [comment]
深谷さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◎ユーザーの新規登録ができませんでした。
パスワードに数字と小英字を入れてユーザー登録できない。
[https://gyazo.com/f5a0e066f31d7a8c684b64f31780d874](https://gyazo.com/f5a0e066f31d7a8c684b64f31780d874)

◎これは不備ではないですが、出品されている商品が少なく感じます。
３点以上出品しましょう。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Resy31** [comment]
挙動確認ありがとうございます。
ご指摘いただいた箇所ですが、

・ユーザーの新規登録ができないに関してですが、半角英数混同でバリデーションを組んでおり、私の方の環境では数字と半角英字での登録は確認できました。
再度ご確認お願いしてもよろしいでしょうか？

・出品されている商品数は増やしました！

以上、よろしくお願いします。

**Comment by mc-nakayama** [comment]
深谷さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
